const TodoActions = {
  ADD_TODO: 'ADD_TODO',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  DELETE_TOD0:'DELETE_TODO',
  TOGGLE_COMPLETED_ALL: 'TOGGLE_COMPLETED_ALL',
  TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',
  EDIT_TODO: 'EDIT_TODO',
  SET_TODOS: 'SET_TODOS',
};

export default TodoActions;